# -*- coding:UTF-8 -*-
import smtplib
from email.mime.image import MIMEImage
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.header import Header
from threading import Thread
import socket,os
import time




class emailThread(Thread):
    def __init__(self,func,args=()):
        Thread.__init__(self)
        self.func = func
        self.args = args

    def run(self):
        self.result = self.func(*self.args)

    def get_result(self):
        Thread.join(self)
        try:
            return True
        except Exception:
            return False



sender = 'tbai@bliulab.net'  # 发送邮件的人
receivers = 'yadxbt@163.com'  # 接收邮件人

# 第三方SMTP服务
# mail_host='smtp.exmail.qq.com'  # 设置发送服务器
# mail_user = 'tbai@bliulab.net'  # 登录邮箱名
# mail_pass = 'CPSgSfE7oSY7taJ5'  # 口令（授权码）YADX@bt312021

def send_async_email( mail_host,mail_user,mail_pass, toaddr, body, attachment):
    # 三个参数：第一个是文本内容，第二个plain设置文本格式，第三个utf-8设置编码
    message = MIMEMultipart()  # 发送邮件正文
    message['From'] = Header(mail_user)  # 发送者
    message['To'] = Header(toaddr)    # 接收者
    subject = 'Results from ncRNALocate' # 发送邮件标题
    message['Subject'] = Header(subject)
    message.attach(MIMEText(body,'html'))
    message.attach(attachment)
    try:
        smtpObj = smtplib.SMTP_SSL(mail_host, 465)  # 发送服务器的端口号
        smtpObj.login(mail_user, mail_pass)
        smtpObj.sendmail(mail_user, toaddr, message.as_string())
        return True
    except smtplib.SMTPException:
        return False


def send_email(webserver,url, download_path, user_email):
    if user_email != '':
        From_mail_user = 'tbai@bliulab.net'  # 登录邮箱名
        From_mail_pass = 'CPSgSfE7oSY7taJ5'  # 口令（授权码）YADX@bt312021
        To_mail_user = user_email
        mail_host = 'smtp.exmail.qq.com'
        body = ''
        body +=    '<p>Dear user,<br/><br />'+ \
                   'Attached please find the results generated by '+ webserver +' web-server. You can also access the results by clicking <font color="#123456"><b>'+ url +'</b><font> <br/><br />'+ \
                   'Thank you for using  '+ webserver +'  !<br /><br />'+ \
                   'With best regards,<br />'+ \
                   'Bioinformatics Group<br />'+ \
                   'School of Computer Science and Technology <br> Beijing Institute of Technology, Beijing 100081, China <br/> </p>'               
        with open(download_path, 'r') as f:
            attachment = MIMEText(f.read())
            attachment.add_header('Content-Disposition', 'attachment', filename='result.txt')          
        try:
            thread = emailThread(send_async_email,args=(mail_host,From_mail_user,From_mail_pass, To_mail_user, body, attachment))
            thread.start()
            return thread.get_result()
        except socket.gaierror:
            pass
        except smtplib.SMTPServerDisconnected:
            pass
        except smtplib.SMTPException:
            pass
    else:
        return False

if __name__ == "__main__":
    webserver = 'ncRNALocate'
    path='./temp/user/127.0.0.1_lncRNA_1658058757.94/file.txt'
    url = 'www.baidu.com'
    flag = send_email(webserver,url,path,receivers)
    if flag :
        print("邮件发送成功")